### ISSUE TITLE
Fix tests that sometimes fail

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/simona#359]
Some tests usually succeed, but sometimes don't (e.g. under high cpu load, some timeouts are set too low).

**Comment by sebastian-peter** [comment]
Examples:

(this first one happens a lot)
```
- must return valid log messages for each status event *** FAILED *** (10 seconds, 354 milliseconds)
  java.lang.AssertionError: Timeout (10 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(INFO),None,None,Some(Simulating from 2011-01-01 00:00:00 until 2011-01-01 01:00:00.),None,None,Map(),true,None).
  at akka.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:103)
  at edu.ie3.simona.event.listener.RuntimeEventListenerSpec.$anonfun$new$5(RuntimeEventListenerSpec.scala:155)
  at edu.ie3.simona.event.listener.RuntimeEventListenerSpec.$anonfun$new$5$adapted(RuntimeEventListenerSpec.scala:151)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at edu.ie3.simona.event.listener.RuntimeEventListenerSpec.$anonfun$new$4(RuntimeEventListenerSpec.scala:151)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  ...
```

```
- should start the simulation, do 2 sweeps and should end afterwards when no deviation on nodal power is recognized in the superior when a StartGridSimulationTrigger is send *** FAILED *** (4 seconds, 22 milliseconds)
  java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg:
  at scala.Predef$.assert(Predef.scala:279)
  at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:479)
  at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:476)
  at akka.testkit.TestKit.expectMsgPF(TestKit.scala:973)
  at edu.ie3.simona.agent.grid.DBFSAlgorithmSupGridSpec.$anonfun$new$6(DBFSAlgorithmSupGridSpec.scala:189)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
  at edu.ie3.simona.agent.grid.DBFSAlgorithmSupGridSpec.$anonfun$new$5(DBFSAlgorithmSupGridSpec.scala:148)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

```
- should write a series of new NodeResults to Kafka *** FAILED *** (22 seconds, 213 milliseconds)
  The code passed to eventually never returned normally. Attempted 13 times over 21.375327958000003 seconds. Last failure message: List() had length 0 instead of expected length 3. (ResultEntityKafkaSpec.scala:156)
  org.scalatest.exceptions.TestFailedDueToTimeoutException:
  ...
  at edu.ie3.simona.io.result.ResultEntityKafkaSpec.$anonfun$new$2(ResultEntityKafkaSpec.scala:156)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1239)
  ...
  Cause: org.scalatest.exceptions.TestFailedException: List() had length 0 instead of expected length 3
  ...
  at edu.ie3.simona.io.result.ResultEntityKafkaSpec.$anonfun$new$3(ResultEntityKafkaSpec.scala:160)
  at org.scalatest.enablers.Retrying$$anon$4.makeAValiantAttempt$1(Retrying.scala:184)
  at org.scalatest.enablers.Retrying$$anon$4.tryTryAgain$2(Retrying.scala:196)
  at org.scalatest.enablers.Retrying$$anon$4.retry(Retrying.scala:226)
  at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:313)
  at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:312)
  at edu.ie3.simona.io.result.ResultEntityKafkaSpec.eventually(ResultEntityKafkaSpec.scala:43)
```

```
  - should shutdown and compress the data when requested to do so without any errors *** FAILED *** (10 seconds, 386 milliseconds)
    java.lang.AssertionError: assertion failed: timeout 10 seconds expired:
    at scala.Predef$.assert(Predef.scala:279)
    at akka.testkit.TestKitBase.poll$1(TestKit.scala:300)
    at akka.testkit.TestKitBase.awaitCond(TestKit.scala:306)
    at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:289)
    at akka.testkit.TestKit.awaitCond(TestKit.scala:973)
    at edu.ie3.simona.event.listener.ResultEventListenerSpec.$anonfun$new$37(ResultEventListenerSpec.scala:563)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
    at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    ...
```

**Comment by staudtMarius** [comment]
I found another one.
    
    - should process a valid participants result correctly *** FAILED *** (10 seconds, 23 milliseconds)
          java.lang.AssertionError: assertion failed: timeout 10 seconds expired:
          at scala.Predef$.assert(Predef.scala:279)
          at akka.testkit.TestKitBase.poll$1(TestKit.scala:300)
          at akka.testkit.TestKitBase.awaitCond(TestKit.scala:306)
          at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:289)
          at akka.testkit.TestKit.awaitCond(TestKit.scala:973)
          at edu.ie3.simona.event.listener.ResultEventListenerSpec.$anonfun$new$7(ResultEventListenerSpec.scala:192)  
          at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
          at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
          at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
          at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
          ...
