### ISSUE TITLE
NoSuchFileException at vnSimona

### ISSUE THREAD

**Issue by danielfeismann** [ie3-institute/simona#643]
running vnSimona arises the following error
steps:

- [ ] find out why this happens
- [ ] fix it accordingly  
- [ ] the exception should idealy name the missing file as well
- [ ] to be discussed: depending on what is missing, this exception should maybe lead to a failing simulation run

 

```
13:56:30.121 INFO  e.i.s.e.l.RuntimeEventListener$ - Initializing Agents and Services for Simulation ... 
13:56:30.138 ERROR e.i.d.io.connectors.CsvFileConnector - Unable to determine time series files readers for time series.
java.nio.file.NoSuchFileException: input\samples\vn_simona\fullGrid\input\samples\vn_simona\fullGrid
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at edu.ie3.datamodel.io.connectors.CsvFileConnector.getIndividualTimeSeriesFilePaths(CsvFileConnector.java:238)
	at edu.ie3.datamodel.io.connectors.CsvFileConnector.getCsvIndividualTimeSeriesMetaInformation(CsvFileConnector.java:212)
	at edu.ie3.datamodel.io.source.csv.CsvTimeSeriesMetaInformationSource.<init>(CsvTimeSeriesMetaInformationSource.java:42)
	at edu.ie3.simona.service.primary.PrimaryServiceProxy.createSources(PrimaryServiceProxy.scala:206)
	at edu.ie3.simona.service.primary.PrimaryServiceProxy.edu$ie3$simona$service$primary$PrimaryServiceProxy$$prepareStateData(PrimaryServiceProxy.scala:149)
	at edu.ie3.simona.service.primary.PrimaryServiceProxy$$anonfun$uninitialized$1.applyOrElse(PrimaryServiceProxy.scala:116)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at edu.ie3.simona.service.primary.PrimaryServiceProxy.aroundReceive(PrimaryServiceProxy.scala:85)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by sebastian-peter** [comment]
Probably caused by this: https://github.com/ie3-institute/PowerSystemDataModel/issues/886

**Comment by danielfeismann** [comment]
Exception is no longer present, thus closing this issue.
